language: ruby
rvm:
  - 2.3.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
install:
  - cd engines/board && bundle install --jobs=3 --retry=3 --deployment
script:
  - bundle exec rake && cd engines/board && bundle exec rake

