language: ruby
rvm:
  - 2.3.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - cd engines/board && bundle install
script:
  - bundle exec rake && cd engines/board && bundle exec rake

